name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: go build

    - name: Test
      run: go test ./...
