name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.23.0'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: go build

    - name: Test
      run: go test ./...
